version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: express-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:v1.8
    container_name: express-mail
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  postgres_data: